### ISSUE TITLE
Can you show an example of testing a simple node module

### ISSUE THREAD

**Issue by dearfrankg** [inossidabile/grunt-testem-mincer#12]
This isn't doing it for me:

```
      node:
        src: [
          'spec/node/**/*.*'
        ]
        options:
          launchers:
            Node:
              command: "jasmine-node spec/node"
          parallel: 8
          launch_in_dev: ['Node'],
          launch_in_ci: ['PhantomJS', 'Chrome', 'Firefox', 'Safari', 'IE7', 'IE8', 'IE9']

```
